### PR TITLE
Added a package.json so that it can be used with npm and webpack

### PR DESCRIPTION
**Pull request by CurtisHumphrey**

### CODE REVIEW

**Comment by iambumblehead** [comment]
+1

**Comment by BHSPitMonkey** [comment]
Correct me if I'm wrong, but this doesn't seem to actually be enough to make this work (since NoSleep.js isn't a proper module and doesn't provide exports). I installed your fork using `npm install CurtisHumphrey/NoSleep.js` and could not find a way to trick it into working.

**Comment by BHSPitMonkey** [comment]
I made a fork here which works as a Node module (but no longer works standalone or with bower) as a quick hack to use in my personal project, but maybe something along these lines can get merged upstream in a nice way (perhaps UMD): https://github.com/BHSPitMonkey/NoSleep.js

**Comment by vitalets** [comment]
thanks a lot @BHSPitMonkey !
Because with weback 2 it's impossible to load original NoSleep either with `imports-loader` and `script-loader`.

**Comment by richtr** [comment]
npm + webpack will be incorporated in to this project in https://github.com/richtr/NoSleep.js/pull/33.

**Pull request closed without merging**
