### PR TITLE
Use longer blank media files to improve CPU load

### PR DESCRIPTION
**Pull request by ViRPo**
I have noticed several issues (that are already closed) discussing huge CPU load when NoSleep is enabled

We recently noticed issues with that as well

There is one issue, where user jampy suggested using his media files: https://github.com/richtr/NoSleep.js/issues/23
These files, however, never made it to the build, and I would like to change that

I made a comparison of CPU load on my MBP 2016 i5 visible on this (lame) picture

cpu-load-comparison

Blue rectangles mark when NoSleep.js was enabled and running before and pink mark what it looks like after

Downside of this change is the size, from 6,792 bytes to 12,530 bytes

IMO the CPU load improvements heavily outweigh the increase in file size

### CODE REVIEW

**Comment by ViRPo** [comment]
Let me post one more, a bit nicer, picture

image

This is a graph consisting of 4 CPU cores and their load and the app was ran twice (with installation and configuration in between)
I first let the app run idle and then triggered `NoSleep.enable()`
The exact timing of `NoSleep.enable()` is marked with blue lines

**Comment by ianshade** [comment]
Awesome improvement on PCs. Do you have any data on how it performs across smartphones?

**Comment by ViRPo** [comment]
@ianshade I have not performed any tests on smartphones, sorry, but I expect the result to be very much the same

**Comment by hyun-park** [comment]
Exactly what I needed from NoSleep.js. Thank you so much, @ViRPo.

**Comment by a-warner** [comment]
I'd love to see this merged; I just spent quite a while trying to track down performance issues on a webapp that were fixed by removing / disabling nosleep

**Comment by timtribers** [comment]
Can't wait to use the latest version of this lib (thx for all the hard work recently @richtr), but unfortunately I'm stuck on v0.8 - if I move to any later release I get the problem of maxed out CPU in Chrome (on Windows) [issue #66].  I take it that the video file changed after that release.  Does it need this PR to fix it?

**Comment by Danue1** [comment]
I can't wait this PR.

**Comment by pmcilreavy** [comment]
Any indication when this will be merged? This CPU issue is killing me.

**Comment by mhmo91** [comment]
Why is this still open?

**Comment by mhmo91** [comment]
@richtr  would u mind take a look at this... thanks for your great contribution to the open source market, but this is seriously damaging APPs perfromance!

**Comment by Danue1** [comment]
This is merged? HOLY YEAH!

**Pull request closed without merging**
