### PR TITLE
Check that video tag is supported as expected

### PR DESCRIPTION
**Pull request by ArnaudBuchholz**
I faced this issue when testing with Windows Safari 5.1.7
I thought it might be interesting to check that the video tag is actually working.

### CODE REVIEW

**Comment by ArnaudBuchholz** [comment]
However, I was not able to build using the webpack command

**Comment by richtr** [comment]
Thanks for the PR!

I think this single line of code is getting too long and corrupts the meaning of the `oldIOS` const.

Could we split this check out to a separate `const hasVideoSupport` value and then create another `const useFallback = oldIOS || !hasVideoSupport` instead? Then we should replace checks for `oldIOS` throughout the code with `useFallback` too?

WDYT?

**Comment by richtr** [comment]
Does the fallback approach work on Windows Safari 5.1.7?

**Comment by ArnaudBuchholz** [comment]
I agree with (and like) your approach. I will make the necessary change soon.
Regarding your second question: it seems to work partly (my old iPhone 4 sometimes go back to /).

**Comment by richtr** [comment]
@ArnaudBuchholz I think we will close this issue unless we could split that first line out somehow. Is this still an issue worth addressing?

**Comment by ArnaudBuchholz** [comment]
@richtr Sorry for the delay... I close.

**Pull request closed without merging**
