### PR TITLE
Fix library to work with latest Android/iOS updates

### PR DESCRIPTION
**Pull request by richtr**
This pull request fixes some recent issues with the library no longer working with the latest devices. 

Tested and working on:

* Android 6.0.1 (+ Chrome 59)
* iOS 10.3 (Safari + Chrome)

That is an admittedly _tiny_ sample size but that is also all the devices I have to hand right now. If anyone else is interested in testing this please post your results in this thread.

I plan to merge to master barring any showstoppers in the next couple of days.

### CODE REVIEW

**Comment by richtr** [comment]
How to test:

1. Clone this repo on your local machine: `git clone https://github.com/richtr/NoSleep.js.git && cd NoSleep.js`
2. Checkout this branch: `git checkout feature/latest-device-updates`
3. Start a simple local web server with your technology of choice https://gist.github.com/willurd/5720255 (e.g. `npm install -g node-static && static -p 8080`)
4. Install [ngrok](https://ngrok.com/) and run with the same port used in step 2 above: `ngrok http 8080`.
5. Load `<NGROK_URL>/example.html` on your devices to test.

**Comment by vespino** [comment]
Sorry, I don't use git, but if you link to the file I can use, I would gladly test. Is it this file? https://github.com/richtr/NoSleep.js/blob/master/NoSleep.min.js

**Comment by richtr** [comment]
@vespino This is the file: https://github.com/richtr/NoSleep.js/blob/b10685cfe373025aaaa5119a52fec30406d202e5/NoSleep.js.

If you install `git` on your machine and run the commands exactly as above that should also be straightforward.

**Comment by vespino** [comment]
@richtr doesn't work for me unfortunately.

**Comment by richtr** [comment]
What device are you testing on? It works for me on iOS 10.3.2 with both Safari and Chrome browsers.

**Comment by vespino** [comment]
iPhone 7 plus, latest iOS ... I have copied the code to a new file and added it to my project. Next I have used this code:

```
var noSleep = new NoSleep();
noSleep.enable();
```

Do I need to do more?

**Comment by richtr** [comment]
Please see the usage instructions in the [README](https://github.com/richtr/NoSleep.js#usage).

The call to `noSleep.enable()` must be wrapped in a user input event handler e.g. a mouse or touch handler. So when the user clicks or touches the screen, the library can work.

**Comment by vespino** [comment]
Ok, I followed to instructions, but it only seems to work after touching the screen, right? I would like to have it load at document ready. Is that possible?

**Comment by richtr** [comment]
No it is not possible with the current solution.

**Comment by GeertVanWonterghem** [comment]
Agreed, but what about if you touch to have a wake lock, then manually put your mobile in standby and then awake again. It would be handy if it has a wake lock again then. Do you think this is possible?

**Comment by richtr** [comment]
> Agreed, but what about if you touch to have a wake lock, then manually put your mobile in standby and then awake again. It would be handy if it has a wake lock again then. Do you think this is possible?

**Pull request merged**
