### PR TITLE
rework autoplay: set it by attributes

### LINKED ISSUE #19: Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.
This message I receive on Android Chrome while do 
NoSleep.enable()

And NoSleep does not work

### PR DESCRIPTION
**Pull request by adarrra**
fix #19 
Hi!
We can add attribute `autoplay` along with `muted` and it would work without user gesture.
I red that this solution should  work for iOS and Android.
https://developers.google.com/web/updates/2016/07/autoplay
https://webkit.org/blog/6784/new-video-policies-for-ios/

I tested mobile android Chrome and Firefox. It works fine.
Also I changed logic to 'loop' attribute because current solution created glitch in Firefox  - added and removed play/pause to dash menu constantly.
Unfortunately I haven't iOS device to test.
Also I added one devDeps because build didn't run on my machine  without it.

### CODE REVIEW

**Comment by richtr** [comment]
Thanks for the PR!

I think we are going to have to look at a number of things before merging. Unfortunately there are many problems related to iOS.

The latest updates to `master` come from observing/reverse engineering the sleep rules used by Webkit to determine if the display should remain awake or sleep: https://github.com/WebKit/webkit/blob/933086c8c2e6330df4e72e3b77ddc3c322e45f65/Source/WebCore/html/HTMLMediaElement.cpp#L6363-L6392. Other browsers use similar but slightly different rules.

As we can see from that code setting a video to `loop` does not explicitly prevent display sleep on iOS devices. Hence the "constantly seek the video" to prevent display sleep used in the current `master` branch. I also have a feeling setting `muted` to true _could_ have an impact on the functionality. The media.js data URL includes a silent audio track just in case.

What I think we should do is remove the `loop` additions and `muted` attribute addition from this PR but keep the `autoplay` addition in the `enable()` function. That way we should get the benefits of being able to call `enable()` without a user input event without breaking the library's functionality on iOS!

WDYT?

**Comment by richtr** [comment]
We should also probably remove the `autoplay` attribute in the `disable()` function when it is called.

**Comment by richtr** [comment]
> Also I changed logic to 'loop' attribute because current solution created glitch in Firefox - added and removed play/pause to dash menu constantly.

Let's file this as a separate issue and work on this separately.

**Comment by adarrra** [comment]
Hm, I see...

`autoplay` by itself will not work without `mute` attribute. 

> playback will start automatically for a video element once it comes into view if both autoplay and muted are set (Chrome)

> <video> elements will be allowed to play() without a user gesture if their source media contains no audio tracks, or if their muted property is set to true. (Webkit)

It's a pity but I do not into cpp very much, so just want to ask are you sure? I test on my friends iOS:10.2 and it works fine...
Example for test: https://adarrra.github.io/rainbow-light/
Also I do not fully understand what do you mean setting `muted` to true could have an impact on the functionality? Than in iOS silent tracks also do not prevent sleeping?

So what we may do with PR? Create iOS and android separate logic... But maybe it has no sense in this situation... So nothing( I just don't want to use gesture.

**Comment by adarrra** [comment]
Upd: today I found one more friend with iOS and yes it doesn't work.

**Pull request closed without merging**
